# Generated by Django 4.1.1 on 2022-09-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonTable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(default=0, max_length=100)),
                ('teamid', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
