# Generated by Django 4.1.1 on 2022-09-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonTable', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member',
            field=models.CharField(default='', max_length=100),
        ),
    ]
