# Generated by Django 4.1.1 on 2022-09-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonTable', '0004_team_table_alter_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jointeam',
            field=models.CharField(default=-1, max_length=100),
        ),
    ]
